### ISSUE TITLE
Director necessary?

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-jira#28]
Hi all,
is the director necessary to run this module?
I installed ipl 0.4.0, incubator 0.3.0, cloned the master of jira and get the following issues:
![image](https://user-images.githubusercontent.com/7324088/67672262-de72ca00-f977-11e9-90ce-f0cb3fb0d7d4.png)
![image](https://user-images.githubusercontent.com/7324088/67672298-eaf72280-f977-11e9-8471-406506e485c9.png)

Cheers,
Marcus

**Comment by Thomas-Gelf** [comment]
You're right, thanks for reporting this. v1.0 should have removed all dependencies on the Director, but there are still some leftovers. Will be fixed with v1.0.1.

Cheers,
Thomas

NB: The Director now allows you to completely hide it in the UI with a new config flag:

https://github.com/Icinga/icingaweb2-module-director/issues/2007

**Comment by Thomas-Gelf** [comment]
@MarcusCaepio: could you please give it another try?

**Comment by MarcusCaepio** [comment]
Hi @Thomas-Gelf 
I will try it as soon as I am back in the office and will give you feedback.
I am on vacation for the next 2 weeks :)

Cheers,
Marcus

**Comment by Thomas-Gelf** [comment]
Thanks @MarcusCaepio, enjoy your vacation!
