### ISSUE TITLE
How to configure plugin in distributed environment?

### ISSUE THREAD

**Issue by gomesar** [Icinga/icingaweb2-module-jira#46]
Hi,
we are having troubles with Jira notifications, I think it happens because the notifications is tried to be sent by the core1/core2 but the module is installed in another host (icingaweb).

our setup consists in:
icingaweb  -> icingacore1/ icingacore2 -> icingasat1/ icingasat2 / icingasat3 

Can you help me with any extra configuration?

Maybe I can create a new zone with only icingaweb and config Jira notifications to be sent by this zone?

_____
`Command` is default.

Jira Notification Template:
```
template Notification "JIRA ServiceCrit Homolog" {
    command = "JIRA Service Notification"
}
```

Jira Notification:
```
apply Notification "JIRA Service Crit" to Service {
    import "JIRA ServiceCrit Homolog"

    times = {
        begin = 5s
    }
    interval = 0s
    assign where match("check*", service.name) && match("*homolog*", host.name)
    states = [ Critical ]
    types = [ Custom, Problem ]
    users = [ "tester" ]
    vars.jira_ack_author = "JIRAUSER"
    vars.jira_description = "Teste de chamado automatico"
    vars.jira_issuetype = "Incident"
    vars.jira_project = "CH"
    vars.notification_useremail = "$user.email$"
}

```

**Comment by Thomas-Gelf** [comment]
Notifications are usually being sent from the Master Zone only - unless configured otherwise. You need to have a minimal Icinga Web installation on your core1/core2, with the Jira module being enabled and configured. You should also configure the monitoring module for full functionality - with a configured Command Transport, to have Icinga ACKnowledges created once a Jjira issue has been created. Alternatively you can also pass the path to a legacy Icinga Command Pipe to the notification command - that way you could skip the monitoring module.
